/* #define _GNU_SOURCE */
#undef MODULE_FILES
#undef MODULE_SHADOW
#undef MODULE_KRB5
#undef MODULE_LDAP
#undef MODULE_SASLDB
#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_STPCPY
#undef HAVE___SECURE_GETENV
#undef HAVE_LC_MESSAGES
