AM_CFLAGS = @GLIB_CFLAGS@ \
	-I$(top_srcdir)/include \
	-I$(top_srcdir)/intl \
	-I/usr/include/python1.5 \
	-DLOCALEDIR=\"`eval echo $(datadir)/locale`\" \
	-DMODULEDIR=\"`eval echo $(pkglibdir)`\" \
	-DSYSCONFDIR=\"`eval echo $(sysconfdir)`\" 
