/* Automatically generated by po2tbl.sed from libuser.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Feature not implemented: ", 2},
  {"NOT creating home directory '%s'.\n", 3},
  {"NOT moving %s to %s.\n", 4},
  {"NOT removing %s.\n", 5},
  {"[OPTION...] user", 6},
  {"No user name specified.\n", 7},
  {"User %s does not exist.\n", 8},
  {"Minimum:\t%d\n", 9},
  {"Maximum:\t%d\n", 10},
  {"Warning:\t%d\n", 11},
  {"Inactive:\t%d\n", 12},
  {"Never", 13},
  {"Last Change:\t%s\n", 14},
  {"Password Expires:\t%s\n", 15},
  {"Password Inactive:\t%s\n", 16},
  {"Account Expires:\t%s\n", 17},
  {"Aging information for %s could not be modified.\n", 18},
  {"[OPTION...] group", 19},
  {"No group name specified.\n", 20},
  {"Group creation failed.\n", 21},
  {"Group %s does not exist.\n", 22},
  {"Group %s could not be deleted.\n", 23},
  {"Both -L and -U specified.\n", 24},
  {"Group %s could not be locked.\n", 25},
  {"Group %s could not be unlocked.\n", 26},
  {"Group %s could not be modified.\n", 27},
  {"Error creating group for %s.\n", 28},
  {"Account creation failed.\n", 29},
  {"Bad UID for %s.\n", 30},
  {"Bad GID for %s.\n", 31},
  {"No home directory for %s.\n", 32},
  {"Error creating %s.\n", 33},
  {"User %s could not be deleted.\n", 34},
  {"%s did not have a home directory.\n", 35},
  {"Error removing %s.\n", 36},
  {"Error reading old home directory for %s.\n", 37},
  {"User %s could not be locked.\n", 38},
  {"User %s could not be unlocked.\n", 39},
  {"User %s could not be modified.\n", 40},
  {"No old home directory for %s.\n", 41},
  {"No new home directory for %s.\n", 42},
  {"Error moving %s to %s.\n", 43},
  {"error loading libuser module '%s': %s.", 44},
  {"no initialization function %s in '%s'.", 45},
  {"error initializing '%s'.", 46},
  {"module version mismatch in %s", 47},
  {"Could not open configuration file '%s'.", 48},
  {"dump of struct lu_ent at %p:\n", 49},
  {" magic = %08x\n", 50},
  {"\
\n\
Before copy:\n", 51},
  {"\
\n\
After copy:\n", 52},
  {"freeing lu_ent at %p.\n", 53},
  {"Error initializing lu.\n", 54},
  {"Searching for group with ID %d.\n", 55},
  {"Searching for group named %s.\n", 56},
  {"Searching for user with ID %d.\n", 57},
  {"Searching for user named %s.\n", 58},
  {"Entry not found.\n", 59},
  {"Default user object classes:\n", 60},
  {"Default user attribute names:\n", 61},
  {"Getting default user attributes:\n", 62},
  {"Copying user structure:\n", 63},
};

int _msg_tbl_length = 63;
