#!/usr/bin/python
import quota
import os

user = "nalin"

quota.on()
quotas = quota.get(quota.USER, user)
print quotas.keys()
for key in quotas.keys():
	item = quotas[key]
	print item.special + ":"
	print " inodes (usage, soft limit, hard limit, grace period) = ",
	print item.inode_usage, item.inode_soft,
	print item.inode_hard, item.inode_grace
	print " blocks (usage, soft limit, hard limit, grace period) = ",
	print item.block_usage, item.block_soft,
	print item.block_hard, item.block_grace
	save = item.copy()

item.inode_soft = 102400
item.inode_hard = 204800
item.inode_grace = 300
item.block_soft = 102400
item.block_hard = 204800
item.block_grace = 300

print("Manipulating quota structure (before):")
print save
print("Manipulating quota structure (after):")
print item

print("Before setting quota:")
os.system("quota -v -u " + user);
quota.set(item)
print("After setting quota:")
os.system("quota -v -u " + user);
quota.set(save)
print("After resetting quota:")
os.system("quota -v -u " + user);
