#!/usr/bin/python

import libuser

print "--------- Initializing."
admin = libuser.Admin()

print "--------- Lookup."
ldap = admin.lookupUserByName("ldap")

print "--------- Reading attribute (get)."
print ldap.get("loginShell")
print "--------- Reading attribute (map)."
print ldap["loginShell"]
print "--------- Reading keys."
print ldap.keys()

print "--------- Setting attribute."
ldap.set("loginShell", ["/bin/true"])
#ldap["loginShell"] = "/bin/true"
#ldap["loginShell"] = ["/bin/true"]

print "--------- Reading attribute (get)."
print ldap.get("loginShell")
print "--------- Reading attribute (map)."
print ldap["loginShell"]

print "--------- Getting directory list."
dir(ldap)

print "--------- Modifying user."
admin.modifyUser(ldap)
